### PR TITLE
fix: person-centric relationship to user

### LINKED ISSUE #12: [Bug] In the people graph, child-parent relations act differently on me vs spouse vs child
## Describe the bug

In the people graph, child-parent relations act differently on me vs spouse vs child.
Arrows and relations are different for both parents when viewing the child graph. 

## To Reproduce

1. Add 2 people : a spouse, and a child.
Image

2. Go in the spouse's profile, and add a relationship. Choose Child, and select the child.
Image

Nayiri is now identified as the parent of the child in the graph:
Image

But the relations table indicate child:
Image

In the child's graph, he has a parent and a child, with arrows point from or to the child:
Image

And the Relationships table indicate two relationships, a parent and a child:
Image

In the "all" graph, we see the same parent & child relationships, but with child relationshop arrow inverted, versus what is seen above:
Image

## Expected behavior

In the child graph, both parents should have the same relationship with the child, either the parents are the parents of the child, or the child is the child of both parents.  
In the all graph, if the arrows both point from or to the child, the labels on the arrows should be the same.

## Environment

- nametag version: v0.12.3

### PR DESCRIPTION
**Pull request by Zangetsu101**
## Summary
The relationship with the user is now consistent with the other relationships shown in a person's relationships section.

image

Now both the user and Nayiri Piloyan are listed as "Parent" whereas previously the user was listed as "Child" and Nayiri Piloyan as "Parent" which was wrong.

## Checklist

- [x] I've run tests locally
- [x] I've updated documentation where needed (added comments)
- [x] I've added/updated tests for the change (if applicable) (existing tests are passing)
- [x] I've considered backwards compatibility / migrations (if applicable) (no breaking changes)
- [x] **I've added/updated translations in ALL locale files** (`/locales/en.json` and `/locales/es-ES.json`) for any new or modified user-facing strings (none modified)

## Screenshots (if UI changes)

image

image

image

- Arrows are now hidden by default. They are revealed along with the relationship labels, when a person is focused.
- Graph now contains both the forward and inverse relationships when available.
- Hovering over a person now highlights all the direct relationships with the other people in the graph.

## Related issues

Closes #12

### CODE REVIEW

**Comment by Zangetsu101** [comment]
@mattogodoy The current change solves one part of the issue, by showing the inverse relationship with the user, it now follows the same direction used for the relationships with other people.

As for the other part, regarding the graph, I think just showing one relationship direction using the "lexicographical" sorting will one way or another clash with the relationships listed in the person details page or introduce inconsistency in the relationship directions in the dashboard page.

What do you think about adding both directions of the relationships to the graph and only highlighting the ones going out of a focused node? 

Visually the arrows will be hidden similarly to the relationship labels, and show up as going out from a node when focused.

**Comment by Zangetsu101** [comment]
@mattogodoy Would really appreciate a review and approval to run the workflows 🙏

File: app/api/people/[id]/graph/route.ts [hunk 1]
```diff
@@ -120,128 +126,79 @@ export const GET = withAuth(async (_request, session, context) => {
...
-            target: targetId,
-            type: relationshipLabel,
-            color: relationshipColor || '#999999',
-          });
+    person.relationshipsFrom
+      .map(relationshipToGraphEdge)
+      .filter((e) => e !== undefined)
+      .forEach((e) => {
+        if (!includedEdges.has(`${e.source}-${e.target}`)) {
+          edges.push(e);
```
Comment (mattogodoy) [inline app/api/people/[id]/graph/route.ts]: (see previous comment)
This is 3/4:

```suggestion
          edges.push(e);
          includedEdges.add(`${e.source}-${e.target}`);
```

File: app/api/people/[id]/graph/route.ts [hunk 2]
```diff
@@ -120,128 +126,79 @@ export const GET = withAuth(async (_request, session, context) => {
...
-    });
+      });
+
+    // include the inverse relationships too
+    person.relationshipsFrom
+      .map(inverseRelationshipToGraphEdge)
+      .filter((e) => e !== undefined)
+      .forEach((e) => {
+        if (!includedEdges.has(`${e.source}-${e.target}`)) {
+          edges.push(e);
```
Comment (mattogodoy) [inline app/api/people/[id]/graph/route.ts]: (see previous comment)
This is 4/4:

```suggestion
          edges.push(e);
          includedEdges.add(`${e.source}-${e.target}`);
```

**Review by mattogodoy — CHANGES_REQUESTED** [review]
We're almost there!
Take a look at the comments and let me know what you think :)
